[package]
name = "surrealix-core"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
surrealdb = { version = "1.0.0", features = ["kv-mem"] }
tokio = "1.38.0"
